version: "2"
services:
  dbus:
    image: balenablocks/dbus
    restart: always
    privileged: true
  client:
    restart: always
    build: ./client
    privileged: true
    depends_on:
      - custom-service
  custom-service:
    restart: always
    build: ./custom-service
    privileged: true
    depends_on:
      - dbus
